### ISSUE TITLE
Cortex M4 (Adafruit Grand Central ATSAMD51)

### ISSUE THREAD

**Issue by hanyazou** [skx/z80retroshield#7]
Hi,

I got a Z80 Retro Shield and was looking for a good sample and found your project.
I was able to get BASIC working right away. Very useful project.
Thank you very much.

Next I ran your project on an AT SAMD51 (Cortex M4 120MHz) board instead of an AT Mega 2560.
It ran fast.

My working branch on my github includes these changes below,
https://github.com/hanyazou/z80retroshield/commits/adafruit-grand-central-samd51
* Support for the Adafruit Grand Central M4 board
https://learn.adafruit.com/adafruit-grand-central
* Added debug output
* Faster operation (the speed_test says 1,263K cycles per second)
* Simple and tiny bug fixes

If you are interested in this fix I would like to send you a PR.
Please take a look at my branch.

Best regards.

12:43:52.226 -> Z80 configured to run endless stream of NOPs.
12:43:52.226 -> Cycle/Second will be dumped once per second.
12:43:52.226 -> Cycles per second second:63
12:43:52.991 -> Cycles per second second:1262937
12:43:54.019 -> Cycles per second second:1263436
12:43:55.020 -> Cycles per second second:1263236
12:43:56.016 -> Cycles per second second:1263336
12:43:56.997 -> Cycles per second second:1263436

![SAMD51-RetroShield-Z80](https://user-images.githubusercontent.com/493387/208280993-97f198bd-3bdd-4465-9c08-55608eaea790.jpg)

**Comment by skx** [comment]
Sorry for the slow reply, and thanks for your "issue".  

I'd be absolutely willing to include the changes you describe - my only requirement is that it would continue to run on the Mega which I use myself, now and again.  Other than that constraint anything is welcome!

**Comment by hanyazou** [comment]
Thank you for the reply.

> my only requirement is that it would continue to run on the Mega

I've tried all examples and it seemed to run some degree on my Mega and METRO M4. For example, type PRINT "HELLO" on the basic show "HELLO". But I'm not sure EVERY thing is running perfectly because I don't know how it will works canonically.

I would like to test any behavior that should be tested. Do you have any idea of features that should be tested?

**Comment by skx** [comment]
Then that's good enough, it was more a caveate if there are any significant/invasive changes that I'd still like it work for the mega - because that's what I use, when I do do anything!

**Comment by hanyazou** [comment]
I wrote test script and checked your examples on Mega and Metro M4.
They seemed to be OK on my Mega. I found that it was very unstable on my Metro M4 however.
I think I must investigate some hardware issues and it would take long time.

I made a PR of my changes except Metro M4 porting.
This includes test script, debugging function and so on. These changes are also useful for the Mega. 
Please look at https://github.com/skx/z80retroshield/pull/8

I close this issue.
